from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import smtplib
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from datetime import datetime
import config

app = Flask(__name__, static_folder='.')
CORS(app)

@app.route('/')
def index():
    with open('index.html', 'r', encoding='utf-8') as f:
        return f.read()

@app.route('/send-violation', methods=['POST'])
def send_violation():
    try:
        data = request.get_json()

        violation_type = data.get('type', 'UNKNOWN')
        timestamp      = data.get('timestamp', str(datetime.now()))
        latitude       = data.get('lat', 'N/A')
        longitude      = data.get('lng', 'N/A')
        image_data     = data.get('image', '')

        # Decode image
        if ',' in image_data:
            image_data = image_data.split(',')[1]
        image_bytes = base64.b64decode(image_data)

        # Build email
        msg = MIMEMultipart()
        msg['From']    = config.EMAIL
        msg['To']      = config.EMAIL
        msg['Subject'] = f"🚨 Traffic Eye Alert: {violation_type} — {timestamp}"

        gps_link = f"https://maps.google.com/?q={latitude},{longitude}" if latitude != 'N/A' else 'Unavailable'

        body = f"""
Traffic Eye Violation Report
==============================
Type      : {violation_type}
Time      : {timestamp}
Latitude  : {latitude}
Longitude : {longitude}
Maps Link : {gps_link}

This report was auto-generated by Traffic Eye.
        """.strip()

        msg.attach(MIMEText(body, 'plain'))

        # Attach image
        img = MIMEImage(image_bytes, _subtype='jpeg')
        img.add_header('Content-Disposition', 'attachment', filename=f'violation_{int(datetime.now().timestamp())}.jpg')
        msg.attach(img)

        # Send via Gmail SMTP
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
            smtp.login(config.EMAIL, config.APP_PASSWORD)
            smtp.send_message(msg)

        print(f"[✓] Email sent for: {violation_type} at {timestamp}")
        return jsonify({'success': True})

    except Exception as e:
        print(f"[✗] Error: {e}")
        return jsonify({'success': False, 'error': str(e)}), 500


@app.route('/ping', methods=['GET'])
def ping():
    return jsonify({'status': 'Traffic Eye server running'})


if __name__ == '__main__':
    print("🚦 Traffic Eye Flask server starting on http://localhost:5000")
    app.run(host='0.0.0.0', port=5000, debug=False)